go run . "hello"
go run . "HELLO"
go run . "HeLlo HuMaN"
go run . "1Hello 2There"
go run . "Hello\nThere"
go run . "{Hello & There #}"
go run . "hello There 1 to 2!"
go run . "MaD3IrA&LiSboN"
go run . "1a\"#FdwHywR&/()="
go run . "{|}~"
go run . "[\]^_ 'a"
go run . "RGB"
go run . ":;<=>?@"
go run . "\!\" #$%&'()*+,-./"
go run . "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
go run . "abcdefghijklmnopqrstuvwxyz"

echo -e "\e[30;1;45mTESTS WITH RANDOM STRINGS\033[0m"
go run . "RNDtext"
go run . "lower 90"
go run . "A~-="
go run . "ab  1./,TRY"

