echo "Preparation"
go run . "Hello World" "--output=example00.txt"
go run . "123" "--output=example01.txt"
go run . "#=\[" "--output=example02.txt"
go run . "(somthing&234)" "--output=example03.txt"
go run . "abcdefghijklmnopqrstuvwxyz" "--output=example04.txt"
go run . "\!\" #$%&'()*+,-./" "--output=example05.txt"
go run . ":;<=>?@" "--output=example06.txt"
go run . "ABCDEFGHIJKLMNOPQRSTUVWXYZ" "--output=example07.txt"

echo "Start Testing"
go run . "--reverse=example00.txt"
go run . "--reverse=example01.txt"
go run . "--reverse=example02.txt"
go run . "--reverse=example03.txt"
go run . "--reverse=example04.txt"
go run . "--reverse=example05.txt"
go run . "--reverse=example06.txt"
go run . "--reverse=example07.txt"
